services:
  rabbit:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "15671:15671"
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=password
